name: checks
on: [pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install uv
        run: |
          echo "export PATH=\$HOME/.cargo/bin:\$PATH" >> $GITHUB_ENV
          make uv-install
      - name: Install dependencies
        run: make install
      - name: Run pre-commit checks
        run: make lint
      - name: Run ruff checks
        run: make test
